version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: reservation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation-service-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reservation-network
      - bookfair-network

  reservation-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: reservation-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reservation-service-db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    networks:
      - reservation-network
      - bookfair-network

volumes:
  mysql_data:

networks:
  reservation-network:
    driver: bridge
  bookfair-network:
    external: true